### ISSUE TITLE
App crashing on boot

### ISSUE THREAD

**Issue by 2xAA** [Rinnegatamante/rct-vita#2]
Hi, I've followed all the instructions and the app is not booting.

Just crashes with a generic error "C2-12828-1".
The only deviance from the README instructions is that I'm using AutoPlugin II for my plugin management and it's using `ur0` instead of `ux0`.

I'm also not using FdFix as I'm using rePatch, as instructed.

I'm using the vpk from the Homebrew Browser, not GitHub.

Would uploading the crash dump be of use to you?

Thanks.

**Comment by Rinnegatamante** [comment]
Either data files are not properly placed or AutoPlugin II fucked up something like it always does and which is why every respectable person in the scene says NOT to use it. The coredump would be of little usage.

**Comment by 2xAA** [comment]
Data files look to be okay, I've previously used `raider-vita` which has been great.
I'll take a look at moving away from AutoPlugin II, had no idea it was a bad choice. Thanks.

**Comment by Rinnegatamante** [comment]
You need libfmodstudio for rct-vita unlike raider-vita beware.

**Comment by 2xAA** [comment]
Already extracted and placed in `ur0:/data`.

I'm surprised it's not working since raider-vita is.
I'll double check the assets, but I've got all the .ogg files in `ux0:/data/rct/assets` as per the README.

**Comment by 2xAA** [comment]
It was an assets issue - closing!
